### ISSUE TITLE
Error installing pycrypt on Raspberry Pi 3

### ISSUE THREAD

**Issue by johnforeland** [Noctem/pycrypt#2]
So after the latest commit, the -march=native argument when compiling with gcc is causing an error on Raspberry Pi 3 due to cpu auto-detection not working there (see https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091&p=922980)

It says I could update gcc to gcc6, but then the gcc6 command must be used, as gcc will still be the old one. It also says this fix is backborted to gcc4, but raspbian has not updated it yet.

Would it be possible to check if using a Raspberry PI 2/3 after setup.py:11, then instead of adding "**-march=native**", add "**-march=armv8-a**" for RPi3 only or "**-march=armv6**" (or just remove -march=native option) to build for all RPis. (copy pasted from url above)

Error when installing:
```
  building 'pycrypt' extension
  creating build
  creating build/temp.linux-armv7l-2.7
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7.13/include/python2.7 -c pycrypt.c -o build/temp.linux-armv7l-2.7/pycrypt.o -O3 -march=native
  error: command 'gcc' terminated by signal 6
  
  ----------------------------------------
  Failed building wheel for pycrypt
  Running setup.py clean for pycrypt
Failed to build pycrypt
Installing collected packages: pycrypt
  Running setup.py install for pycrypt ... -*** Error in `gcc': double free or corruption (top): 0x00807fb0 ***
error
    Complete output from command /home/pi/pogo/RocketMap/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-U_cb5L/pycrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-njl2Lb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/pogo/RocketMap/venv/include/site/python2.7/pycrypt:
    running install
    running build
    running build_ext
    building 'pycrypt' extension
    creating build
    creating build/temp.linux-armv7l-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7.13/include/python2.7 -c pycrypt.c -o build/temp.linux-armv7l-2.7/pycrypt.o -O3 -march=native
    error: command 'gcc' terminated by signal 6
    
    ----------------------------------------
Command "/home/pi/pogo/RocketMap/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-U_cb5L/pycrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-njl2Lb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/pogo/RocketMap/venv/include/site/python2.7/pycrypt" failed with error code 1 in /tmp/pip-build-U_cb5L/pycrypt/
```

**Comment by johnforeland** [comment]
Okay, gcc6 was pretty easily installed and even replaced gcc4. But maybe a fix should be implemented, as Raspbian only includes gcc 6.9.2 (and needs at least 6.9.4) and you need to change /etc/apt/sources.list in order to upgrade.

**Comment by j16sdiz** [comment]
This is a GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132

**Comment by Noctem** [comment]
You can work around this by setting `TRAVIS` in your environment before installing if your compiler can't handle `march=native` properly:
```bash
export TRAVIS=1
```

**Comment by Noctem** [comment]
Worked around in b665333d5b61f9a6c5a0d7068b07e1016f192945. I've also provided a [binary wheel for Python 3.6 on ARMv7](https://github.com/Noctem/pycrypt/releases/download/v0.7.2/pycrypt-0.7.2-cp36-cp36m-manylinux1_armv7l.whl).
